### ISSUE TITLE
CSRF Token necessary?

### ISSUE THREAD

**Issue by BuriKizilkaya** [rust10x/rust-web-app#21]
Is it necessary to have an csrf token to prohibt form submit from different domain.

**Comment by jeremychone** [comment]
Very good one, let me work on this. Will be in next `0.1.1` release.

**Comment by jeremychone** [comment]
Sorry, my previous answer was about another repo/issue.

It's tricky to answer that. If you have a security team, you might want to build a simple CSRF token. It doesn't have to be a fully-fledged token, but something that can change over time. It could even be in the code. The trick is to handle the rollout/roll-in.

Now, technically speaking, since we're using `application/json`, `POST` requests are pre-flighted by the browser, meaning the browser will try to check the "OWASP" rules before doing the full post. So, if OWASP is set up, it should be fine. Now, if the default rules are in place, meaning if OWASP is not present, I think the browser will be conservative and not perform an HTTP POST on `application/json` to another domain. But this needs to be verified.

If you have file uploads with multipart form data, it's probably better to have CSRF protection.

Security is about multi-layering, so to be extra safe:

1) Ensure everything is `application/json` and HTTP POST, which JSON-RPC enforces, and other endpoints should do the same (even if not using JSON-RPC).
2) Make sure to define the OWASP rules—this is something I should add to this repo.
3) For extra layering, add CSRF in the UI (and backend for validation). It doesn't have to be a fully-fledged token as mentioned above. It could just be a UUID or something similar in the codebase. In fact, one simple technique would be to have an array of them (hardcoded). Let's say you keep the three most recent, and when you want to update, you add one and remove the oldest. This way, the UI will always have a "recent" enough CSRF, and even if you update the backend and the frontend isn't updated, it will still work by using the two older ones. Hope this makes sense. But validate the scheme with your security team.

**Comment by BuriKizilkaya** [comment]
Thank you for your detailed reply. 

In your blueprint you have the approach to have json-rpc and I like it when I built a server that should have API (JSON payload). I think to build a blueprint to use HTMX + Rust with some of your approaches like the authtenication. I saw in some threads that if I use SameStrict in the cookie I can prevent CSRF attacks.

**Comment by jeremychone** [comment]
@BuriKizilkaya Yes, I think `SameStrict` is the restrictive one to set to make sure there cannot be cross-site calls (when pre-flighted).

As long as all your HTTP calls are POST with content type `application/json`, they will be pre-flighted by the browser and denied.

So, CSRF is not strictly needed.

However, if you have file uploads, I am not sure if POST multipart is pre-flighted (intuitively, I do not think they are, but I need to check).

Assuming you do not have multipart queries, and all is POST on `application/json`, then it should be technically ok.

Now, having a CSRF scheme, even a very simple one, like a hardcoded value that the client puts back in some header for each request, might be a good additional (not strictly necessary) security layer. It doesn't have to be fancy.
